---
title: "irisDataset"
author: "Elena Machkasova"
date: "4/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## MNIST example

This is just an example that comes with keras installation. MNIST is a database of labelled handwritten digits (stored as small 28-by-28 files).
It already comes with training and testing data. 

## dataframes

```{r}
library(keras3)
library(tfdatasets)


#Loading a csv file
irisdf <- read.csv("iris.csv")

# Various syntax for R dataframes
summary(irisdf)

head(irisdf)

# You can refer to columns by name or by number:
head(irisdf[,1]) # head takes the first few elements

head(irisdf$sepal.length)

head(irisdf["sepal.length"])
```

```{r}
#You can refer to rows by numbers, note difference from columns:
irisdf[5,]

#Ranges of columns:
head(irisdf[,1:3])

#Ranges of rows:
irisdf[1:3,]
```

## Data preprocessing

```{r}

# Changing strings to categories

# Nested ifelse doesn't work on a column, so we use 3 functions, applied one by one: 

catToNum1 <- function(c) {
  ifelse (c == "Setosa",0,c) 
}


catToNum2 <- function(c) {
  ifelse (c == "Versicolor",1,c)
}

catToNum3 <- function(c) {
  ifelse (c == "Virginica",2,c)
}

# Testing the functions

catToNum1("Setosa")
catToNum2("Versicolor")
catToNum3("Banana")

# Note: changes it in place! 
# Also the function is applied to the entire column - many (but not all) functions in R may be used this way
irisdf[5] <- lapply(irisdf[5],catToNum1)
irisdf[5] <- lapply(irisdf[5],catToNum2)
irisdf[5] <- lapply(irisdf[5],catToNum3)
irisdf[5] <- lapply(irisdf[5],strtoi) # Apparently the category numbers in irisdf[5] are stored as strings; convert to numbers

# plotting variety (as numbers) vs sepal.length
plot(irisdf$sepal.length, irisdf$variety, xlab = "Sepal length", ylab = "Variety")

head(irisdf)
```

## Splitting data into training and testing

```{r}
sample_size <- 120
set.seed(1234) # setting random seed to make results repeatable

picked <- sample(seq_len(nrow(irisdf)),size = sample_size)
training <- irisdf[picked,]
testing <- irisdf[-picked,]


# Changing y into categorical data (performing one-hot encoding)

yTr <- to_categorical(training$variety, num_classes = 3)
yTest <- to_categorical(testing$variety, num_classes = 3)

yTest

```

## Neural network for the iris example

```{r}

model = keras_model_sequential() %>%
  layer_dense(units = 64, activation = "relu",input_shape=(4)) %>%
  layer_dense(units = 64, activation = "relu") %>%
  layer_dense(units = ncol(yTr), activation = "softmax")


model %>% compile(
  loss = "categorical_crossentropy",
  optimizer = "adam", 
  metrics = "accuracy"
)

xTr <- as.matrix(training[,1:4]) # need to convert to a matrix
xTest <- as.matrix(testing[,1:4])

model %>% 
  fit(
    x = xTr, # input is the first 4 columns of the dataframe
    y = yTr, # label is the last column
    epochs = 20
  )

```

# Evaluate the model

```{r}
model %>% evaluate(xTest, yTest)

# Predicting likelihood of all categories:
result <- model %>% predict(xTest)

result

testing[,5]

```
